// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: etStQC96WVyQomtXYtyAGu
// Component: XJnQYWQqy5QL
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: etStQC96WVyQomtXYtyAGu/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: XJnQYWQqy5QL/css
import Rectangle7Icon from "./icons/PlasmicIcon__Rectangle7"; // plasmic-import: FoZ5VCf5jW/icon
import MinimizeIcon from "./icons/PlasmicIcon__Minimize"; // plasmic-import: eSsA3Fo1Wq/icon
import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: ykB-xpxi_B/icon
import QuestionCircleFill1Icon from "./icons/PlasmicIcon__QuestionCircleFill1"; // plasmic-import: z9XZ5Bb0V1/icon
import Facebook1Icon from "./icons/PlasmicIcon__Facebook1"; // plasmic-import: NM2R4OUWIb/icon
import Youtube1Icon from "./icons/PlasmicIcon__Youtube1"; // plasmic-import: dbnA210WvE/icon
import Github1Icon from "./icons/PlasmicIcon__Github1"; // plasmic-import: iUzun64XrH/icon
import Twitter1Icon from "./icons/PlasmicIcon__Twitter1"; // plasmic-import: OeJjEMjhsy/icon
import Stackoverflow1Icon from "./icons/PlasmicIcon__Stackoverflow1"; // plasmic-import: Via7Yzss-CR/icon
import CartFill1Icon from "./icons/PlasmicIcon__CartFill1"; // plasmic-import: EytB46pgiUZ/icon
import GearWideConnected1Icon from "./icons/PlasmicIcon__GearWideConnected1"; // plasmic-import: -xR7MjMySzu/icon
import PeopleFill1Icon from "./icons/PlasmicIcon__PeopleFill1"; // plasmic-import: mQNX-sYXCA4/icon
import CodeSlash1Icon from "./icons/PlasmicIcon__CodeSlash1"; // plasmic-import: nCkZtVCP34o/icon
import CheckCircleFill11Icon from "./icons/PlasmicIcon__CheckCircleFill11"; // plasmic-import: IVUAcvQ4yew/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

export const defaultHomepage__Args = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultHomepage__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"ubuntuBudgieWelcome"}
          data-plasmic-override={overrides.ubuntuBudgieWelcome}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.ubuntuBudgieWelcome
          )}
        >
          <div
            data-plasmic-name={"ubuntuWindow"}
            data-plasmic-override={overrides.ubuntuWindow}
            className={classNames(projectcss.all, sty.ubuntuWindow)}
          >
            <div
              data-plasmic-name={"applicationArea"}
              data-plasmic-override={overrides.applicationArea}
              className={classNames(projectcss.all, sty.applicationArea)}
            />

            <Rectangle7Icon
              className={classNames(projectcss.all, sty.svg__ilaNc)}
              role={"img"}
            />

            <div
              data-plasmic-name={"rectangle8"}
              data-plasmic-override={overrides.rectangle8}
              className={classNames(projectcss.all, sty.rectangle8)}
            />

            <div
              data-plasmic-name={"titleBar"}
              data-plasmic-override={overrides.titleBar}
              className={classNames(projectcss.all, sty.titleBar)}
            >
              <div
                data-plasmic-name={"titleBar2"}
                data-plasmic-override={overrides.titleBar2}
                className={classNames(projectcss.all, sty.titleBar2)}
              >
                <div
                  data-plasmic-name={"background"}
                  data-plasmic-override={overrides.background}
                  className={classNames(projectcss.all, sty.background)}
                />

                <div
                  data-plasmic-name={"windowControls"}
                  data-plasmic-override={overrides.windowControls}
                  className={classNames(projectcss.all, sty.windowControls)}
                >
                  <MinimizeIcon
                    className={classNames(projectcss.all, sty.svg__kdNut)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"maximize"}
                    data-plasmic-override={overrides.maximize}
                    className={classNames(projectcss.all, sty.maximize)}
                  >
                    <div
                      data-plasmic-name={"rectangle3"}
                      data-plasmic-override={overrides.rectangle3}
                      className={classNames(projectcss.all, sty.rectangle3)}
                    />
                  </div>

                  <div
                    data-plasmic-name={"close"}
                    data-plasmic-override={overrides.close}
                    className={classNames(projectcss.all, sty.close)}
                  >
                    <div
                      data-plasmic-name={"rectangle2"}
                      data-plasmic-override={overrides.rectangle2}
                      className={classNames(projectcss.all, sty.rectangle2)}
                    />

                    <XIcon
                      className={classNames(projectcss.all, sty.svg__aelIx)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"application"}
                data-plasmic-override={overrides.application}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.application
                )}
              >
                {"Ubuntu Budgie Welcome"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wEc7W
              )}
            >
              {"Main Menu"}
            </div>

            <div
              data-plasmic-name={"ubuntuBudgieIcon2451"}
              data-plasmic-override={overrides.ubuntuBudgieIcon2451}
              className={classNames(projectcss.all, sty.ubuntuBudgieIcon2451)}
            />

            <div
              data-plasmic-name={"rectangle4"}
              data-plasmic-override={overrides.rectangle4}
              className={classNames(projectcss.all, sty.rectangle4)}
            />

            <div
              data-plasmic-name={"_1200PxUbuntuBudgieWordmark1"}
              data-plasmic-override={overrides._1200PxUbuntuBudgieWordmark1}
              className={classNames(
                projectcss.all,
                sty._1200PxUbuntuBudgieWordmark1
              )}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aOu0Y
              )}
            >
              {"Choose an option to discover your new operating system"}
            </div>

            <div
              data-plasmic-name={"rectangle5"}
              data-plasmic-override={overrides.rectangle5}
              className={classNames(projectcss.all, sty.rectangle5)}
            />

            <div
              data-plasmic-name={"rectangle11"}
              data-plasmic-override={overrides.rectangle11}
              className={classNames(projectcss.all, sty.rectangle11)}
            />

            <div
              data-plasmic-name={"rectangle12"}
              data-plasmic-override={overrides.rectangle12}
              className={classNames(projectcss.all, sty.rectangle12)}
            />

            <div
              data-plasmic-name={"rectangle9"}
              data-plasmic-override={overrides.rectangle9}
              className={classNames(projectcss.all, sty.rectangle9)}
            />

            <div
              data-plasmic-name={"rectangle10"}
              data-plasmic-override={overrides.rectangle10}
              className={classNames(projectcss.all, sty.rectangle10)}
            />

            <div
              data-plasmic-name={"rectangle13"}
              data-plasmic-override={overrides.rectangle13}
              className={classNames(projectcss.all, sty.rectangle13)}
            />

            <div
              data-plasmic-name={"rectangle14"}
              data-plasmic-override={overrides.rectangle14}
              className={classNames(projectcss.all, sty.rectangle14)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aCNt3
              )}
            >
              {"Introduction"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tZaQp
              )}
            >
              {"Features"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__gQpBw
              )}
            >
              {"Getting Started"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cvzh
              )}
            >
              {"Recommendations"}
            </div>

            <QuestionCircleFill1Icon
              className={classNames(projectcss.all, sty.svg__eyjCr)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4LPob
              )}
            >
              {"Online Store"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aJkft
              )}
            >
              {"Get Involved"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jlhXg
              )}
            >
              {"Community"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ojz5F
              )}
            >
              {"Donate"}
            </div>

            <Facebook1Icon
              className={classNames(projectcss.all, sty.svg__mlnfJ)}
              role={"img"}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__uqCnw)}
              displayHeight={"256px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"256px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blank_project/images/ubuntuBudgieNoWordmark1.svg",
                fullWidth: 256,
                fullHeight: 256,
                aspectRatio: 1
              }}
            />

            <Youtube1Icon
              className={classNames(projectcss.all, sty.svg__srhr)}
              role={"img"}
            />

            <Github1Icon
              className={classNames(projectcss.all, sty.svg__oBHh)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__irA0S
              )}
            >
              {"Get Support"}
            </div>

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__nmpc)}
              displayHeight={"41.904px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"172px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blank_project/images/vlpa.svg",
                fullWidth: 172,
                fullHeight: 41.904,
                aspectRatio: 4.095238
              }}
            />

            <Twitter1Icon
              className={classNames(projectcss.all, sty.svg__sGwyz)}
              role={"img"}
            />

            <Stackoverflow1Icon
              className={classNames(projectcss.all, sty.svg__saIr)}
              role={"img"}
            />

            <CartFill1Icon
              className={classNames(projectcss.all, sty.svg__suQ5Y)}
              role={"img"}
            />

            <GearWideConnected1Icon
              className={classNames(projectcss.all, sty.svg__pWaYm)}
              role={"img"}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__lq4DU)}
              displayHeight={"24px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"24px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blank_project/images/currencyExchange1.svg",
                fullWidth: 24,
                fullHeight: 24,
                aspectRatio: 1
              }}
            />

            <PeopleFill1Icon
              className={classNames(projectcss.all, sty.svg__fMh)}
              role={"img"}
            />

            <CodeSlash1Icon
              className={classNames(projectcss.all, sty.svg__tyBIs)}
              role={"img"}
            />

            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__sAwL)}
              displayHeight={"24px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"24px"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blank_project/images/infoCircleFill1.svg",
                fullWidth: 24,
                fullHeight: 24,
                aspectRatio: 1
              }}
            />

            <CheckCircleFill11Icon
              className={classNames(projectcss.all, sty.svg__dmxlX)}
              role={"img"}
            />
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  ubuntuBudgieWelcome: [
    "ubuntuBudgieWelcome",
    "ubuntuWindow",
    "applicationArea",
    "rectangle8",
    "titleBar",
    "titleBar2",
    "background",
    "windowControls",
    "maximize",
    "rectangle3",
    "close",
    "rectangle2",
    "application",
    "ubuntuBudgieIcon2451",
    "rectangle4",
    "_1200PxUbuntuBudgieWordmark1",
    "rectangle5",
    "rectangle11",
    "rectangle12",
    "rectangle9",
    "rectangle10",
    "rectangle13",
    "rectangle14"
  ],

  ubuntuWindow: [
    "ubuntuWindow",
    "applicationArea",
    "rectangle8",
    "titleBar",
    "titleBar2",
    "background",
    "windowControls",
    "maximize",
    "rectangle3",
    "close",
    "rectangle2",
    "application",
    "ubuntuBudgieIcon2451",
    "rectangle4",
    "_1200PxUbuntuBudgieWordmark1",
    "rectangle5",
    "rectangle11",
    "rectangle12",
    "rectangle9",
    "rectangle10",
    "rectangle13",
    "rectangle14"
  ],

  applicationArea: ["applicationArea"],
  rectangle8: ["rectangle8"],
  titleBar: [
    "titleBar",
    "titleBar2",
    "background",
    "windowControls",
    "maximize",
    "rectangle3",
    "close",
    "rectangle2",
    "application"
  ],

  titleBar2: [
    "titleBar2",
    "background",
    "windowControls",
    "maximize",
    "rectangle3",
    "close",
    "rectangle2"
  ],

  background: ["background"],
  windowControls: [
    "windowControls",
    "maximize",
    "rectangle3",
    "close",
    "rectangle2"
  ],

  maximize: ["maximize", "rectangle3"],
  rectangle3: ["rectangle3"],
  close: ["close", "rectangle2"],
  rectangle2: ["rectangle2"],
  application: ["application"],
  ubuntuBudgieIcon2451: ["ubuntuBudgieIcon2451"],
  rectangle4: ["rectangle4"],
  _1200PxUbuntuBudgieWordmark1: ["_1200PxUbuntuBudgieWordmark1"],
  rectangle5: ["rectangle5"],
  rectangle11: ["rectangle11"],
  rectangle12: ["rectangle12"],
  rectangle9: ["rectangle9"],
  rectangle10: ["rectangle10"],
  rectangle13: ["rectangle13"],
  rectangle14: ["rectangle14"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ubuntuBudgieWelcome") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("ubuntuBudgieWelcome"),
  {
    // Helper components rendering sub-elements
    ubuntuWindow: makeNodeComponent("ubuntuWindow"),
    applicationArea: makeNodeComponent("applicationArea"),
    rectangle8: makeNodeComponent("rectangle8"),
    titleBar: makeNodeComponent("titleBar"),
    titleBar2: makeNodeComponent("titleBar2"),
    background: makeNodeComponent("background"),
    windowControls: makeNodeComponent("windowControls"),
    maximize: makeNodeComponent("maximize"),
    rectangle3: makeNodeComponent("rectangle3"),
    close: makeNodeComponent("close"),
    rectangle2: makeNodeComponent("rectangle2"),
    application: makeNodeComponent("application"),
    ubuntuBudgieIcon2451: makeNodeComponent("ubuntuBudgieIcon2451"),
    rectangle4: makeNodeComponent("rectangle4"),
    _1200PxUbuntuBudgieWordmark1: makeNodeComponent(
      "_1200PxUbuntuBudgieWordmark1"
    ),

    rectangle5: makeNodeComponent("rectangle5"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle13: makeNodeComponent("rectangle13"),
    rectangle14: makeNodeComponent("rectangle14"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
